POST http://66.219.198.205:443/v1/users HTTP/1.1
content-type: application/json

{
    "alias": "lane$example.com",
    "password": "Newuser@1",
    "create_user_password": "somepassword"
}

###

POST http://66.219.198.205:443/v1/auth HTTP/1.1
content-type: application/json

{
    "alias": "lane$example.com",
    "password": "Newuser@1"
}

###

PUT http://66.219.198.205:443/v1/addresses HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkb21haW4iOiJleGFtcGxlLmNvbSIsInVzZXJuYW1lIjoibGFuZSIsImV4cCI6MTU0MzQ1NjIzMywiaWF0IjoxNTQzNDU0NDMzLCJpc3MiOiJleGFtcGxlLmNvbSJ9.7zfcGbeHLW7QYjLF9kIMrWDBr_kWYuUQDp-rw9-NIAQ

{
    "address_type": 300,
    "address": "xrb_3xnpp3eh6fhnfztx46ypubizd5q1fgds3dbbkp5ektwut3tumrykyx6u5qpd"
}

###

http://66.219.198.205:443/v1/addresses?alias=lane$example.com&address_type=300
